version: '3'

services:
  server:
    image: nginx
    volumes:
      - ./api:/var/www/html
      - .docker/nginx/default:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 80:80
    networks:
      - backend
      - frontend

  node:
    build: .docker/node
    image: node
    ports:
      - 8080:8080
    volumes:
      - ./app:/home/node/app:rw
    user: "node"
    working_dir: /home/node/app
    command: bash -c "npm install && npm run prod"
    networks:
      - frontend

  app:
    build: .docker/php
    image: php:7.2
    volumes:
      - ./api:/var/www/html:rw
    networks:
      - backend

  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: test-bs2
      MYSQL_USER: test-bs2
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - .docker/mysql:/var/lib/mysql
    networks:
      - backend

networks:
  backend:
  frontend: